makesnap
update-to-core22.patch

`electron-builder`, even in its latest iteration, still uses a template that has an out-of-date (End-Of-Life) snap core and gnome version (despite my urging the developers to update it). In order to keep the snap updated any further and keep it seeded in Ubuntu Studio, `electron-builder`'s `app-builder-lib` must be updated to a more current core and gnome version (`core22` and `gnome-42-2204`). Per my testing, Freeshow's snap still functions properly as snapped with this modification.
This PR simply adds a script to make my life easier when updating the snap by automatically patching the `app-builder-lib` component after `npm install` has been executed. Once the patch has been done from the included patch file, it then builds the application and snaps the build.
`electron-builder`'s …

Add snap creation script and patch

---

src/frontend/utils/midi.ts

midi value from the msg (midi in)'s velocity should not be overridden. UI is setting velocity to 0 when it is an index action.
To get midi value-match check working, writing it the other way, from msg (actual midi in) to the midi requirement.
Type wasn't checked too, and should too be checked.

Fix velocity override when only it is no index action, and check type match

---

src/frontend/converters/propresenter.ts

**I've made a fix to address the ProPresenter file import problem. This change fix the decoding function to properly handle negative unicode characters.**
Here's an example with some Chinese characters encoded in negative unicode.
_Before the fix:_
_After the fix:_

Fix ProPresenter file import issue with negative unicode characters

---

makesnap
update-to-core22.patch

Unbeknownst to me, `electron-builder` updated their snap template to `core20`, which only kicks the can down the road by an additional year for them. This keeps freeshow more future-proof by keeping it up-to-date with the latest core and gnome dependencies (`core22` and `gnome-42-2204`).
This also ensures I catch the problem earlier by making the `makesnap` script fail upon error, keying me in that something went terribly wrong and getting my attention sooner.
FYI, the Freeshow snap has already been updated with these changes.

Update makesnap and update-to-core22.patch (fixes #424)

---

src/frontend/converters/opensong.ts

Hi guys, I was importing my songs from OpenSong to FreeShow when I noticed that only the even lines of each verse block was beeing added.
Example of lyrics tag that we currently use:
~~~
<lyrics>[V1]
Noche de paz, noche de amor
Todo duerme en derredor.
Entre los astros que esparcen su luz,
[V2]
Bella anunciando al niñito Jesús,
Brilla la estrella de paz, brilla la estrella de paz.
[V3]
Noche de paz, noche de amor
Oye humilde el fiel pastor.
Coros celestes que anuncian salud,
[V4]
Gracias y glorias en gran plenitud,
//Por nuestro buen Redentor //.
[V5]
¡Noche de paz, 
noche de amor!
Ved qué bello 
resplandor.
[V6]
Luce en el rostro del niño Jesús,
En el pesebre, del mundo la luz,
// Astro de eterno fulgor //.
</lyrics>
~~~
I saw that you had an split on lyrics for chords, I changed it to …

Improvements to open song converter

---

src/frontend/components/show/tools/SlideGroups.svelte

Hi again!
I saw that the show groups where not sorted correctly, because they were sorted by strings and not by the number of the group name so I fixed it
This is the before and after of the change:
Before:
After:

Fix-Show-Groups-Sort

---

src/frontend/converters/powerpoint.ts

Hi guys!
On our church we have a template for power point slides likes this:
To replicate it on FreeShow using the PowerPoint utility we need to have as much text boxes as power point have. For example "Esto es un titulo" is a text box and "I. Amor" Is another text box, with this we can create a template on free show to move every text to the correct position as it is on PowerPoint
Sorry If i didn`t explain it well.
Hope there is no issue on adding this. Thanks! 😄

Create text boxes for every text box on powerpoint

---

src/frontend/components/edit/Editbox.svelte
src/frontend/components/edit/EditboxHelper.ts

- For the first and third bug reported on that issue, wrapping getStyle() in a setTimeout was all that was needed.  Line 655
- For the appropriate line breaks, I added a new helper method to determine which line the cursor should be on when the number of lines change.  I created a new helper class of EditboxHelper and added this function to it, with the intent of expanding that helper class with more functions later.  The goal being to simplify Editbox itself over time, removing any code that doesn't affect the component state.  If this isn't the approach you want to take, feel free to move that function to Editbox instead.
- I haven't attempted it yet, but I think the setTimeout() calls may be a source of a lot of intermittent bugs that are hard to track down.  10ms is adequate when the …

Issue 470 fix

---

src/frontend/components/actions/midi.ts

Not sure why on MacOS, it seems to repeat the same note for all the Midi id, and if we are not checking the channel/note, it will go crazy and execute basically available action.
This add the checks for channel and note, so that it will only fire if the channel and note are matching the action. Not sure if this is the right fix, or if something can be fix on the midi initial dispatching.

Add more checks on whether the note is correct

---

.github/workflows/playwright.yml
README.md
playwright.config.ts

After landing the machine independent e2e test, it enables us to start doing CI on github, as it won't matter with previous setup.
Having the ability to mock out the settings and show data storage, also allows us to test with different preset settings and show data, this allows us to test a few things
- Old settings/show data won't be broken with newer code/testing if migration works.
- Making sure no unexpected UI is showing up with specific settings, i.e. start up screen should show up with old settings.
This allows us to test many more things and will ensure the quality of releases.

Add playwright config and github worklow to run e2e test

---

src/frontend/converters/xml.ts

XML without line breaks is perfectly valid imho so the importer should handle that.

Add xml version tag handling for xml files without newlines

---

src/frontend/converters/openlp.ts

OpenLyrics with more that one title is valid, and title tag can have attributes.
Fixes #656

Handle OpenLyrics titles

---

src/frontend/components/output/layers/BackgroundMedia.svelte

The preview video time stamp is pretty much always a few milliseconds off from the main output.  By trying to bring it back in perfect sync we're making the problem worse because it stalls for a moment when skipping ahead or back, putting it further out of sync.  Doing this dozens of times per second causes the video to stutter.  I updated it to only do this if we're at least 500ms out of sync.

Made preview video time syncing less aggressive

---

README.md

Quick pull request to add python installation instructions. I found that when I had python3.12 installed, I couldn't build FreeShow until I had the `setuputils` python package. Hopefully it helps someone later on :).

Added python installation instructions to building instructions

---

src/tests/start.test.ts

- Add `timeoutMs` constant for consistent timeout handling across tests
- Standardize delay formatting with underscores for readability
- Skip onboarding flow to run current tests without changes
- Adjust locators and remove redundant delays to improve test stability

fix(tests): adjust timeouts and flow to ensure test reliability

---

src/electron/data/export.ts

According to https://www.electronjs.org/docs/latest/api/web-contents#contentsprinttopdfoptions `marginsType` is deprecated.

Fixing PDF export margin

---

snap/snapcraft.yaml

Users who install FreeShow via Snap package (i.e. Ubuntu Store) cannot import/export files to removable media due to the sandboxing.
Fix:
This PR adds "removable-media" to `snapcraft.yaml` so that we (as the publisher of the FreeShow package) indicate that the application _can_ use removable media.
Note:
The user may still need to manually enable the permission, but at least they will now have "removable media" as a permission they can enable. See https://askubuntu.com/a/1267296 and https://snapcraft.io/docs/interface-management#heading--auto-connections

Snap app packaging tweak: Add removable-media to snapcraft.yaml

---

package-lock.json

This is mostly to make my life easier every time I build the snap. Merely changes the `version` line to match the one in `project.json` when `makesnap` is run.

Automate version in snapcraft.yaml

---

src/electron/data/import.ts

This PR changes the `importProject` function to create a new folder named after the current datetime for each project import to avoid name collisions.
Fixes #1227

fix: create a new dir for each project import

---

src/electron/planningcenter/request.ts

I tested the dev branch for the rate-limit issue of planning center, it does not use the retry-after from the header. Apparently the header is lower-case.

retry-after should be lowercase

---

makesnap

The initiative to organize the scripts broke the snap building process. Snaps require a very specific structure and the `snap` directory _must_ be in the root of the repository. WIthout this, it fundamentally breaks.
Additionally, the removal of the executable bit from the scripts caused the entire build to fail as the scripts _must_ be executable in order for the build to succeed and the installed snap to function at all.
I have revised the `makesnap` script to accommodate the changes and move the required files to a `snap` directory during build so it may build properly.

Fix makesnap for commit that organized the scripts

---

makesnap
src/frontend/components/show/TextEditor.svelte
src/frontend/utils/chordTranspose.ts
src/frontend/values/icons.ts

I have gotten the transpose function to work within the text editor, but the save functionality has always been weird and still doesn't work. In production, the save feature often skips small changes such as chord placement, so it might need a revisit.

Adding transpose functionality to text edit (not working fully)

---

config/building/snapcraft.yaml

Since `snapcraft` must be run from the root and since `snapcraft.yaml` must be in the `snap` directory of the root (accommodated by the `makesnap` script), the double-parent sourcing should not be used.

fix 'source' in snapcraft.yaml

---

src/electron/planningcenter/request.ts

Hey there, just thought it would be nice to apply some slight refactoring here to make it easier to maintain.
I was attempting to fix an issue, but wasn't able to figure it out. Maybe someone with more knowledge on the project can help out. For some reason items/songs with the same name are suffixed with a number, even though they are in different Planning Center Plans / FreeShow shows.
The first import goes perfectly fine:
Second one has one minor issue:
But a service with the same template gets quite messy:
If anyone can hint me in the right direction I am more than happy to create a PR for a fix.

slightly refactor loading of Planning Center services

---

src/electron/IPC/responsesMain.ts
src/electron/chums/ChumsConnect.ts
src/electron/data/export.ts
src/electron/data/import.ts
src/electron/planningcenter/connect.ts
src/electron/planningcenter/request.ts
src/electron/utils/keys.ts
src/electron/utils/requests.ts

Will now start the normal Planning Center authentication flow when the refresh token call fails.
Was trying to debug another issue with FreeShow, but Planning Center wouldn't authenticate. Debugged it and figured this could be a solution. Sorry for the accidental formatting changes.

Fix authentication flow when user has old refresh token

---

src/frontend/components/helpers/showActions.ts

Resolves error: "Cannot read properties of undefined (reading 'length')" when get(special).dynamicRSS is undefined by ensuring rssValues is always an array using nullish coalescing operator.
Looks like It fixes this error: https://github.com/ChurchApps/FreeShow/issues/1763

Fix TypeError when dynamicRSS is undefined in getDynamicIds

---

src/frontend/components/edit/editors/SlideEditor.svelte

Last PR I think :)
I think the tranpose options should be available on the Slide Editor when the chords button is pressed. I'm just using the same buttons from texteditor, so I don't know if its the ideal approach but it works fine.

feat: Add tranpose buttons to the Slide Editor

---

src/electron/planningcenter/request.ts

- Ensures consistent line endings.
- Use Planning Center sequence (when available) to create section slides in the order of the arrangement.
Preview of what it does:
Planning Center requires unique labels for sections, that’s why FreeShow auto increments these to `Verse 2 1` and `Verse 2 2`.

Add optional sequencing for Planning Center sections and normalize line endings

---

src/frontend/components/actions/actions.ts
src/frontend/components/helpers/dropActions.ts
src/frontend/components/main/popups/Action.svelte

- Modified dropActions.ts to respect canAddMultiple setting and only replace actions with identical values
- Updated Action.svelte findExisting() to not auto-replace actions that support multiple instances
- Enhanced addSlideAction() in actions.ts to use canAddMultiple from actionData
- Improved createSlideAction() consistency for canAddMultiple handling
Now users can add multiple 'change_stage_output_layout' actions (and other canAddMultiple actions) to a single function/slide, enabling complex workflows like switching between multiple stage layouts sequentially.

Multiple same type actions
